// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DialogContent: typeof import('./../src/components/NaiveUI/src/DialogContent.vue')['default'];
    MessageContent: typeof import('./../src/components/NaiveUI/src/MessageContent.vue')['default'];
    NButton: typeof import('naive-ui')['NButton'];
    NCard: typeof import('naive-ui')['NCard'];
    NCheckbox: typeof import('naive-ui')['NCheckbox'];
    NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
    NForm: typeof import('naive-ui')['NForm'];
    NFormItem: typeof import('naive-ui')['NFormItem'];
    NGrid: typeof import('naive-ui')['NGrid'];
    NGridItem: typeof import('naive-ui')['NGridItem'];
    NInput: typeof import('naive-ui')['NInput'];
    NLayout: typeof import('naive-ui')['NLayout'];
    NLayoutContent: typeof import('naive-ui')['NLayoutContent'];
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter'];
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader'];
    NLayoutSider: typeof import('naive-ui')['NLayoutSider'];
    NMenu: typeof import('naive-ui')['NMenu'];
    NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
  }
}

export {};
